name: dcm
description: A flutter player for Content Management System.
publish_to: "none"

version: 1.0.1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  path: ^1.8.3
  path_provider: ^2.1.1
  provider: ^6.0.3
  file_picker: ^8.3.1
  mime_type: ^1.0.0
  device_info_plus: ^9.0.3
  network_info_plus: ^7.0.0
  storage_info: ^1.0.0
  permission_handler: ^12.0.1
  package_info_plus: ^8.3.0
  intl: ^0.20.2
  open_file: ^3.2.1
  json_annotation: ^4.8.1
  url_launcher: ^6.2.5
  wakelock_plus: ^1.2.11
  window_manager:
    git:
      url: https://github.com/YuiHrsw/window_manager.git
      path: packages/window_manager
      ref: windows_fullscreen_fix

  # Media
  whisper4dart: ^0.1.4
  # libmpv_dart: ^0.0.4

  media_kit: ^1.2.6 # Primary package.
  media_kit_video: ^2.0.1 # For video rendering.
  media_kit_libs_video: ^1.0.7 # Native video dependencies.

  video_player: ^2.11.1
  webview_flutter: ^4.2.2
  webview_flutter_android: ^4.7.0
  webview_flutter_wkwebview: ^3.22.0
  flutter_inappwebview: ^6.1.5
  pointycastle: ^3.7.3
  crypto: ^3.0.6
  xml: ^6.3.0
  # print colorful logs
  # logger: ^2.7.0
  mixin_logger: ^0.1.3
  uuid: ^4.1.0
  isolate_handler: ^1.0.0
  shared_preferences: 2.5.2
  worker_manager: ^7.2.9
  pair: ^0.1.2
  nativeapi: ^0.1.1
  flutter_libserialport:
    path: ./local_flutter_libserialport
  transparent_image: ^2.0.1
  system_info3: ^4.0.2
  image_size_getter: ^2.3.0
  marqueer: ^2.5.0
  flutter_udid: ^4.1.4
  unique_device_identifier: ^2.0.4
  dio: ^5.11.0
  disk_space_2: ^1.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.3.3
  json_serializable: ^6.7.1

flutter:
  assets:
    - res/videos/
    - l10n/
  uses-material-design: true
  generate: true
