buildscript {
    ext.kotlin_version = '2.2.21'
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.11.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:2.2.21"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

ext.kotlin_version = '2.2.21'

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"

    afterEvaluate { evaluatedProject ->
        if (evaluatedProject.plugins.hasPlugin('com.android.library')) {
            if (evaluatedProject.android.namespace == null) {
                evaluatedProject.android.namespace = 'com.gstory.file_preview'
            }
            if (evaluatedProject.name == 'file_preview') {
                evaluatedProject.android.compileSdkVersion = 35
            }
        }
    }
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
